import requests
from bs4 import BeautifulSoup ##html 싹 가져와주는 애
from selenium import webdriver ##웹드라이버 돌려주는애
import pandas as pd
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

firm_df= pd.read_excel('S&P 500 Companies (Standard and Poor 500).xlsx')
firm_df

driver = webdriver.Chrome('/Users/jonghyunkim/repo/Tristan/chromedriver')

url = 'https://www.fool.com/'
driver.implicitly_wait(3) ## 드라이버 실행까지 시간이 좀 있으니 기다려 주는 역할
driver.get(url)

driver.maximize_window()

## 검색창에 원하는 검색어 입력 후 대기
driver.find_element(By.XPATH, '//*[@id="tophat"]/div[1]/input').send_keys('apple inc')
driver.implicitly_wait(4)

# 검색창에 엔터 클릭
driver.find_element(By.XPATH, '//*[@id="tophat"]/div[1]/input').send_keys(Keys.ENTER)
driver.implicitly_wait(4)

Title = driver.find_element(By.XPATH, '/html/body/div[9]/div[3]/div[1]/section[1]/div[1]/header/div/div[2]/h1').text
web_ticker = Title.split(': ')[-1][:-1]
web_ticker

driver.find_element(By.XPATH, '//*[@id="quote-nav"]/div/div[2]/nav/ul/li[8]/a').click()
driver.implicitly_wait(2)

driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button').click()
driver.implicitly_wait(2)

driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button').click()
driver.implicitly_wait(2)

path_list = driver.find_element(By.ID, 'quote-earnings-transcripts').find_elements(By.CLASS_NAME, 'mb-6')
path_list

candidate_list = [path_list[n].text for n in range(len(path_list))]
candidate_list

i = 0
target_indexs = []
for c in candidate_list:
    if '2023' in c:
        target_indexs.append(i)
    elif '2021' in c:
        target_indexs.append(i)

    i += 1
print(target_indexs)

path_list[target_indexs[1]].click()

target_text = driver.find_element(By.CLASS_NAME, 'article-body').text
target_text

driver.back()

driver.quit()

target_text

import re
def cleanhtml(raw_html):
    cleanr = re.compile('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

target_text = target_text.replace('\n', ' ')
target_text

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

vec_reviews = vectorizer.fit_transform([target_text])
vec_terms = vectorizer.get_feature_names_out()
vec_df = pd.DataFrame(vec_reviews.toarray(), columns=vec_terms)
vec_df

# 전 버전

In [16]:
import requests
from bs4 import BeautifulSoup ##html 싹 가져와주는 애
from selenium import webdriver ##웹드라이버 돌려주는애
import pandas as pd
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from sklearn.feature_extraction.text import CountVectorizer

In [17]:
firm_df= pd.read_excel('/Users/jonghyunkim/repo/Tristan/S&P 500 Companies (Standard and Poor 500).xlsx')
firm_df

    Symbol                   Name                  Sector
0      MMM                     3M             Industrials
1      AOS            A. O. Smith             Industrials
2      ABT                 Abbott             Health Care
3     ABBV                 AbbVie             Health Care
4      ACN              Accenture  Information Technology
..     ...                    ...                     ...
516   PENN     Penn Entertainment                     NaN
517     UA  Under Armour(Class C)                     NaN
518    UAA  Under Armour(Class A)                     NaN
519   IPGP          IPG Photonics                     NaN
520    GPS                    Gap                     NaN

[521 rows x 3 columns]

In [53]:
driver = webdriver.Chrome('/Users/jonghyunkim/repo/Tristan/chromedriver')

/var/folders/3m/s0ysqyzs3fb_mcgvm4wjzt3w0000gn/T/ipykernel_42955/118248137.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('/Users/jonghyunkim/repo/Tristan/chromedriver')

In [55]:
driver.maximize_window()
# url = 'https://www.fool.com/'
url = 'https://www.fool.com/quote/nasdaq/aapl/#quote-earnings-transcripts'
driver.get(url)
time.sleep(3)

In [21]:
symbol = []
name = []
web_tickers = []
years = []
quarters = []
target_texts = []
esg_word_count = []
sustainability_word_count = []
res_man_word_count = []

checking = pd.read_excel('SeokJun Collection_체크포인트용.xlsx')
checking2 = pd.read_excel('SeokJun Collection_체크포인트용2.xlsx')
checking3 = pd.read_excel('SeokJun Collection_체크포인트용3.xlsx')
checking4 = pd.read_excel('SeokJun Collection_체크포인트용4.xlsx')
checking5 = pd.read_excel('SeokJun Collection_체크포인트용5.xlsx')
checking6 = pd.read_excel('SeokJun Collection_체크포인트용6.xlsx')


for index, row in firm_df.iterrows():

    if row['Symbol'] in list(checking['Symbol']):
        continue
    elif row['Symbol'] in list(checking2['Symbol']):
        continue

    elif row['Symbol'] in list(checking3['Symbol']):
        continue
    elif row['Symbol'] in list(checking4['Symbol']):
        continue

    elif row['Symbol'] in list(checking5['Symbol']):
        continue
    elif row['Symbol'] in list(checking6['Symbol']):
        continue

    try:
        ## 검색창에 원하는 검색어 입력 후 대기
        driver.find_element(By.XPATH, '//*[@id="tophat"]/div[1]/input').send_keys(row['Name'] + ' ')
        time.sleep(5)

        # 검색창에 엔터 클릭
        driver.find_element(By.XPATH, '//*[@id="tophat"]/div[1]/input').send_keys(Keys.ENTER)
        time.sleep(4)

        Title = driver.find_element(By.XPATH, '/html/body/div[9]/div[3]/div[1]/section[1]/div[1]/header/div/div[2]/h1').text
        web_ticker = Title.split(': ')[-1][:-1]
        if web_ticker != row['Symbol']:
            driver.find_element(By.XPATH, '//*[@id="tophat"]/div[1]/input').send_keys(row['Symbol'] + ' ')
            time.sleep(5)
            driver.find_element(By.XPATH, '//*[@id="tophat"]/div[1]/input').send_keys(Keys.ENTER)
            time.sleep(4)

            Title = driver.find_element(By.XPATH, '/html/body/div[9]/div[3]/div[1]/section[1]/div[1]/header/div/div[2]/h1').text
            web_ticker = Title.split(': ')[-1][:-1]
    except:
        symbol.append(row['Symbol'])
        name.append(row['Name'])
        web_tickers.append(web_ticker)
        years.append('error')
        quarters.append('error')
        target_texts.append('error')
        esg_word_count.append('error')
        sustainability_word_count.append('error')
        res_man_word_count.append('error')
        continue

    time.sleep(2) # 페이지 로딩 대기

    try:
        ## 페이지 좌측 메뉴 바에 Earnings Transcript 라는 버튼 클릭 후 로딩 대기

        # driver.find_element(By.XPATH, '/html/body/div[9]/div[3]/div[1]/section[2]/div/div[1]/div[1]/div').find_element(By.XPATH, "//button[text()='Earnings Transcripts']").click()
        driver.find_element(By.XPATH, '//*[@id="quote-nav"]/div/div[2]/nav/ul/li[8]/a').click()
        time.sleep(2)

        ## 가끔 스크롤 더 혹은 덜 내리는 경우가 잇으니 다시한번 클릭
        driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.PAGE_UP)
        driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.PAGE_UP)
        driver.find_element(By.XPATH, '//*[@id="quote-nav"]/div/div[2]/nav/ul/li[8]/a').click()

        time.sleep(2)

        ## View more earnings transcript 버튼 누르기 2번
        driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button').click()
        time.sleep(2)
        driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button').click()
        time.sleep(2)
    except:
        symbol.append(row['Symbol'])
        name.append(row['Name'])
        web_tickers.append(web_ticker)
        years.append('error')
        quarters.append('error')
        target_texts.append('error')
        esg_word_count.append('error')
        sustainability_word_count.append('error')
        res_man_word_count.append('error')

        continue


    ## 각 earnings transcript의 path 가져오기
    path_list = driver.find_element(By.ID, 'quote-earnings-transcripts').find_elements(By.CLASS_NAME, 'mb-6')

    ## 각 path의 제목들 가져오기 (언제건지 확인용)
    candidate_list = [path_list[n].text for n in range(len(path_list))]


    ## 2023년과 2021년에 해당하는 애들 가져오기
    i = 0
    target_indexs = []
    for c in candidate_list:
        if '2023' in c:
            target_indexs.append(i)
        elif '2021' in c:
            target_indexs.append(i)
        i += 1
    
    for k in target_indexs:
        try:
            path_list[k].click()
        except:
            driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.PAGE_DOWN)
            path_list[k].click()
        time.sleep(2)
        
        symbol.append(row['Symbol'])
        name.append(row['Name'])
        web_tickers.append(web_ticker)

        ## 위에서 가져온 path 제목에서 quarter와 year 골라내서 추가하기
        title_texts = candidate_list[k].split('(' + web_ticker + ')')[1].split()
        quarter = title_texts[0]
        year = title_texts[1]

        years.append(year)
        quarters.append(quarter)
        
        ## 텍스트 가져와서 소문자화 등 전처리 한 후 고유 단어 개수세기
        target_text = driver.find_element(By.CLASS_NAME, 'article-body').text
        target_text = target_text.replace('\n', ' ')
        target_texts.append(target_text)

        target_text = target_text.lower()
        
        vectorizer = CountVectorizer(ngram_range=(1,2))
        vec_reviews = vectorizer.fit_transform([target_text])
        vec_terms = vectorizer.get_feature_names_out()
        vec_df = pd.DataFrame(vec_reviews.toarray(), columns=vec_terms)

        if 'esg' in vec_df.columns:
            esg_count = vec_df['esg']
        else:
            esg_count = 0

        esg_word_count.append(esg_count)

        if 'sustainability' in vec_df.columns:
            sus_count = vec_df['sustainability']
        else:
            sus_count = 0
        
        sustainability_word_count.append(sus_count)


        if 'responsible management' in vec_df.columns:
            res_man_count = vec_df['responsible management']
        else:
            res_man_count = 0
        
        res_man_word_count.append(res_man_count)

        driver.back()
        time.sleep(2)
    
    final_data = pd.DataFrame({'Symbol' : symbol, 'Name' : name, 'Website_ticker' : web_tickers, 'Year' : years, 'Quarter' : quarters, 'Raw Text' : target_texts, 'ESG' : esg_word_count, 'Sustainability' : sustainability_word_count, 'Responsible Management' : res_man_word_count})
    final_data.to_excel('SeokJun Collection_체크포인트용7.xlsx')

In [22]:
driver.quit()

In [24]:
data = pd.concat([checking, checking2, checking3, checking4, checking5, checking6])
data

,Unnamed: 0,Symbol,Name,Website_ticker,Year,Quarter,Raw Text,ESG,Sustainability,Responsible Management
0,0,MMM,3M,MMM,2023,Q4,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,0,"0 4\nName: sustainability, dtype: int64",0
1,1,MMM,3M,MMM,2023,Q3,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,0,"0 2\nName: sustainability, dtype: int64",0
2,2,MMM,3M,MMM,2023,Q2,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,0,"0 2\nName: sustainability, dtype: int64",0
3,3,MMM,3M,MMM,2021,Q4,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,"0 2\nName: esg, dtype: int64","0 11\nName: sustainability, dtype: int64",0
4,4,MMM,3M,MMM,2021,Q3,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,0,"0 9\nName: sustainability, dtype: int64",0
...,...,...,...,...,...,...,...,...,...,...
114,114,GPS,Gap,GPS,2023,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,0,0,0
115,115,GPS,Gap,GPS,2021,Q4,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,"0 1\nName: esg, dtype: int64","0 1\nName: sustainability, dtype: int64",0
116,116,GPS,Gap,GPS,2021,Q3,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,0,"0 1\nName: sustainability, dtype: int64",0
117,117,GPS,Gap,GPS,2021,Q2,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,0,0,0
118,118,GPS,Gap,GPS,2021,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,0,"0 1\nName: sustainability, dtype: int64",0

In [27]:
data.reset_index(inplace=True, drop=True)

In [40]:
data['ESG'][3]

'0    2\nName: esg, dtype: int64'

In [45]:
ESG = []
SUSTAINABILITY = []
RESPONSIBLE_MANAGEMENT = []

for index, row in data.iterrows():
    if row['ESG'] == 'error':
        ESG.append(row['ESG'])
    else:
        if type(row['ESG']) == str:
            ESG.append(row['ESG'].split()[1])
        else:
            ESG.append(row['ESG'])

    if row['Sustainability'] == 'error':
        SUSTAINABILITY.append(row['Sustainability'])
    else:
        if type(row['Sustainability']) == str:
            SUSTAINABILITY.append(row['Sustainability'].split()[1])
        else:
            SUSTAINABILITY.append(row['Sustainability'])

    if row['Responsible Management'] == 'error':
        RESPONSIBLE_MANAGEMENT.append(row['Responsible Management'])
    else:
        if type(row['Responsible Management']) == str:
            RESPONSIBLE_MANAGEMENT.append(row['Responsible Management'].split()[1])
        else:
            RESPONSIBLE_MANAGEMENT.append(row['Responsible Management'])
            

print(len(ESG))
print(len(SUSTAINABILITY))
print(len(RESPONSIBLE_MANAGEMENT))

1108
1108
1108

In [46]:
data['ESG'] = ESG
data['Sustainability'] = SUSTAINABILITY
data['Responsible Management'] = RESPONSIBLE_MANAGEMENT
data

,Unnamed: 0,Symbol,Name,Website_ticker,Year,Quarter,Raw Text,ESG,Sustainability,Responsible Management
0,0,MMM,3M,MMM,2023,Q4,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,0,4,0
1,1,MMM,3M,MMM,2023,Q3,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,0,2,0
2,2,MMM,3M,MMM,2023,Q2,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,0,2,0
3,3,MMM,3M,MMM,2021,Q4,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,2,11,0
4,4,MMM,3M,MMM,2021,Q3,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 5.42%) ...,0,9,0
...,...,...,...,...,...,...,...,...,...,...
1103,114,GPS,Gap,GPS,2023,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,0,0,0
1104,115,GPS,Gap,GPS,2021,Q4,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,1,1,0
1105,116,GPS,Gap,GPS,2021,Q3,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,0,1,0
1106,117,GPS,Gap,GPS,2021,Q2,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,0,0,0
1107,118,GPS,Gap,GPS,2021,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 0.35%)...,0,1,0

In [49]:
data[data['ESG'] == 'error']

,Unnamed: 0,Symbol,Name,Website_ticker,Year,Quarter,Raw Text,ESG,Sustainability,Responsible Management
10,10,ABT,Abbott,ABT,error,error,error,error,error,error
11,11,ABBV,AbbVie,ABBV,error,error,error,error,error,error
16,16,ADBE,Adobe Inc.,ADB,error,error,error,error,error,error
25,25,AES,AES Corporation,AES,error,error,error,error,error,error
26,26,AFL,Aflac,AF,error,error,error,error,error,error
...,...,...,...,...,...,...,...,...,...,...
1087,98,FBHS,Fortune Brands Home & Security,FBH,error,error,error,error,error,error
1088,99,MBC,MasterBrand,MBC,error,error,error,error,error,error
1089,100,PVH,PVH,PVH,error,error,error,error,error,error
1090,101,PENN,Penn Entertainment,PENN,error,error,error,error,error,error
1091,102,UA,Under Armour(Class C),U,error,error,error,error,error,error

In [50]:
data[data['Symbol'] != data['Website_ticker']]

,Unnamed: 0,Symbol,Name,Website_ticker,Year,Quarter,Raw Text,ESG,Sustainability,Responsible Management
16,16,ADBE,Adobe Inc.,ADB,error,error,error,error,error,error
26,26,AFL,Aflac,AF,error,error,error,error,error,error
51,51,ALL,Allstate,AL,error,error,error,error,error,error
106,106,APTV,Aptiv,AMAT,error,error,error,error,error,error
109,109,ANET,Arista Networks,ANAB,error,error,error,error,error,error
...,...,...,...,...,...,...,...,...,...,...
1079,90,SEDG,SolarEdge,SE,2021,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Sea Limited (SE...,0,0,0
1083,94,NWL,Newell Brands,NWTT,error,error,error,error,error,error
1086,97,VNO,Vornado Realty Trust,VN2,error,error,error,error,error,error
1087,98,FBHS,Fortune Brands Home & Security,FBH,error,error,error,error,error,error
1091,102,UA,Under Armour(Class C),U,error,error,error,error,error,error

In [ ]:
data.to_excel()

In [34]:
import FinanceDataReader as fdr
df_nyse = fdr.StockListing('NYSE')
df_nasdaq = fdr.StockListing('NASDAQ')

df_nyse

100%|██████████| 2837/2837 [00:05<00:00, 500.76it/s]
100%|██████████| 3831/3831 [00:06<00:00, 547.36it/s]

,Symbol,Name,Industry,IndustryCode
0,TSM,Taiwan Semiconductor Manufacturing Co Ltd ADR,반도체,57101010
1,LLY,Eli Lilly and Co,제약,56201040
2,V,Visa Inc,온라인 서비스,57201030
3,JPM,JPMorgan Chase & Co,은행,55101010
4,BRK.B,Berkshire Hathaway Inc Class B,소비재 대기업,54401010
...,...,...,...,...
2832,MFAN,MFA Financial 8 875 Senior Notes due 2029,특수 REITs,60102040
2833,RWTN,Redwood Trust 9 125 Senior Notes Due 2029,특수 REITs,60102040
2834,MITN,AG Mortgage Investment Trust 9 500 Senior Note...,특수 REITs,60102040
2835,VATE RT,Innovate Rights Exp 25 March 2024,건설 및 엔지니어링,52201020
2836,CMI WD,Cummins Inc,"자동차, 트럭 및 오토바이 부품",53101020

In [35]:
=

,Symbol,Name,Industry,IndustryCode
0,MSFT,Microsoft Corp,소프트웨어,57201020
1,AAPL,Apple Inc,전화 및 소형 장치,57106020
2,NVDA,NVIDIA Corp,반도체,57101010
3,AMZN,Amazon.com Inc,백화점,53402010
4,META,Meta Platforms Inc,온라인 서비스,57201030
...,...,...,...,...
3826,AFJKR,Aimei Health Technology Rights Exp 17 November...,투자 지주 회사,55601010
3827,PMNT,Perfect Moment Ltd,오락용 제품,53205020
3828,ATLCZ,Atlanticus Holding 9 25 Senior Notes due 2029,소비자 대출,55101030
3829,IROHR,Iron Horse Acquisitions Rights Exp 27 December...,투자 지주 회사,55601010
3830,JVSAR,JV SPAC Acquisition Rights Exp 26th Nov 2026,투자 지주 회사,55601010

In [52]:
nyse_list = list(df_nyse['Symbol'])
nasdaq_list = list(df_nasdaq['Symbol'])
print(nyse_list)

['TSM', 'LLY', 'V', 'JPM', 'BRK.B', 'WMT', 'NVO', 'UNH', 'MA', 'XOM', 'JNJ', 'PG', 'HD', 'BRK.A', 'ORCL', 'ABBV', 'TM', 'MRK', 'CRM', 'CVX', 'BAC', 'KO', 'ACN', 'TMO', 'SAP', 'SHEL', 'ABT', 'WFC', 'DIS', 'MCD', 'NVS', 'BABA', 'DHR', 'GE', 'IBM', 'CAT', 'VZ', 'UBER', 'AXP', 'TTE', 'PFE', 'NOW', 'BX', 'NKE', 'UNP', 'PM', 'MS', 'HSBC', 'HDB', 'BHP', 'RY', 'LOW', 'COP', 'SYK', 'SPGI', 'UPS', 'GS', 'UL', 'PLD', 'BLK', 'T', 'SCHW', 'MUFG', 'NEE', 'RTX', 'ETN', 'ELV', 'PGR', 'MDT', 'TJX', 'BA', 'C', 'UBS', 'BUD', 'TD', 'SONY', 'BMY', 'DE', 'BP', 'CB', 'LMT', 'MMC', 'CI', 'SHOP', 'BSX', 'CVS', 'AMT', 'IBN', 'GSK', 'FI', 'STLA', 'ANET', 'KKR', 'SHW', 'CP', 'HCA', 'WM', 'DEO', 'CNI', 'RELX', 'RACE', 'ZTS', 'INFY', 'RIO', 'ITW', 'ICE', 'CNQ', 'EQNR', 'DELL', 'SMFG', 'TGT', 'ENB', 'MO', 'SO', 'GD', 'SLB', 'CMG', 'SCCO', 'DUK', 'CL', 'EOG', 'MCO', 'TRI', 'SAN', 'BMO', 'PH', 'BTI', 'BDX', 'BN', 'NOC', 'MCK', 'MPC', 'USB', 'APH', 'PSX', 'TDG', 'BBVA', 'TT', 'ECL', 'FDX', 'AON', 'EMR', 'APO', 'EPD', 'FCX', 'BNS', 'PNC', 'AMX', 'NSC', 'RSG', 'CRH', 'MMM', 'PXD', 'MSI', 'HMC', 'EL', 'EW', 'AJG', 'PLTR', 'PBR', 'APD', 'NU', 'OXY', 'COF', 'AZO', 'SNOW', 'VALE', 'SQ', 'VLO', 'WELL', 'HLT', 'MET', 'E', 'CARR', 'DHI', 'ING', 'AIG', 'TRV', 'SPOT', 'ET', 'PSA', 'MFG', 'NGG', 'SPG', 'F', 'TFC', 'AFL', 'STZ', 'GWW', 'CCI', 'COR', 'CM', 'GM', 'IQV', 'SU', 'HES', 'TAK', 'O', 'OKE', 'WMB', 'URI', 'SRE', 'DLR', 'NUE', 'MSCI', 'MFC', 'WCN', 'TEL', 'ALC', 'A', 'KMB', 'STM', 'JCI', 'TRP', 'ALL', 'AME', 'AMP', 'BK', 'HUM', 'FERG', 'ARES', 'MPLX', 'CNC', 'LHX', 'DOW', 'LEN', 'PRU', 'KR', 'D', 'LVS', 'SYY', 'PBR.A', 'FLUT', 'HSY', 'LYG', 'OTIS', 'ABEV', 'FIS', 'KMI', 'NEM', 'HLN', 'KVUE', 'YUM', 'CTVA', 'CMI', 'VEEV', 'GIS', 'MLM', 'IT', 'LNG', 'WDS', 'IR', 'VMC', 'PWR', 'CPNG', 'PCG', 'DG', 'BCS', 'GPN', 'SE', 'CVE', 'ITUB', 'RCL', 'PPG', 'LYB', 'ROK', 'HAL', 'EFX', 'NET', 'SLF', 'BCE', 'PEG', 'HUBS', 'DFS', 'WIT', 'FICO', 'XYL', 'ED', 'EXR', 'DD', 'VICI', 'ORAN', 'HPQ', 'FTV', 'DVN', 'CHT', 'ADM', 'DB', 'HIG', 'PUK', 'CBRE', 'RMD', 'GRMN', 'DAL', 'WST', 'GOLD', 'MTD', 'VRT', 'AEM', 'GLW', 'NWG', 'CAH', 'HWM', 'FMX', 'EIX', 'NTR', 'KEYS', 'AVB', 'ZBH', 'QSR', 'PKX', 'CHD', 'RBLX', 'WEC', 'WY', 'WAB', 'RJF', 'OWL', 'TU', 'TLK', 'RKT', 'DOV', 'NVR', 'BLDR', 'IX', 'GIB', 'BRO', 'ASX', 'PHM', 'LYV', 'EQR', 'MTB', 'TEF', 'DECK', 'BR', 'TRGP', 'MOH', 'PINS', 'AWK', 'CQP', 'TECK', 'IRM', 'STE', 'HPE', 'DTE', 'ROL', 'FNV', 'TS', 'MT', 'STT', 'KB', 'VLTO', 'ETR', 'WRB', 'ARE', 'EC', 'FE', 'APTV', 'BAX', 'INVH', 'FLT', 'HUBB', 'GPC', 'VST', 'IFF', 'UMC', 'DRI', 'WAT', 'IOT', 'ES', 'WPM', 'BALL', 'NOK', 'CTRA', 'TDY', 'TSN', 'PPL', 'MKL', 'SNAP', 'PHG', 'FTS', 'PBA', 'CLX', 'AEE', 'JBL', 'BAH', 'OMC', 'J', 'HRL', 'CCL', 'SHG', 'RS', 'WLK', 'K', 'FDS', 'NMR', 'RCI', 'IEX', 'WSM', 'LH', 'TME', 'BEKE', 'RF', 'TYL', 'JHX', 'TXT', 'SYF', 'CNP', 'ZTO', 'ATO', 'EPAM', 'IHG', 'EXPD', 'VTR', 'BAM', 'CSL', 'CMS', 'AVY', 'EBR', 'MKC', 'LDOS', 'VIV', 'AVTR', 'CE', 'CCJ', 'YUMC', 'AER', 'L', 'LUV', 'GDDY', 'LII', 'EG', 'BBY', 'SUI', 'MAS', 'BF.B', 'PKG', 'H', 'CVNA', 'PSTG', 'WSO', 'CF', 'GGG', 'RTO', 'CFG', 'DPZ', 'EDU', 'SNA', 'ESS', 'MGA', 'CNHI', 'SUZ', 'MAA', 'CRBG', 'DKS', 'TRU', 'TEVA', 'BBD', 'EME', 'RPM', 'EQT', 'MRO', 'LW', 'ALB', 'BEN', 'DGX', 'RYAN', 'BURL', 'XPO', 'SWK', 'OC', 'OVV', 'KEY', 'RBA', 'TKO', 'FNF', 'PATH', 'DT', 'BAP', 'AGR', 'AMCR', 'TOST', 'BIP', 'MGM', 'BBDO', 'GFI', 'BG', 'PNR', 'CAG', 'CRL', 'FND', 'AMH', 'RVTY', 'KMX', 'SJM', 'TAP', 'USFD', 'BLD', 'KIM', 'NRG', 'WES', 'GFL', 'TOL', 'CPB', 'TFII', 'AOS', 'WMS', 'HEI.A', 'IP', 'PR', 'RDY', 'IPG', 'ELS', 'RNR', 'ACM', 'CX', 'WPC', 'TPL', 'NIO', 'UDR', 'DOC', 'RGA', 'SNN', 'DVA', 'ACI', 'WRK', 'CNA', 'NI', 'BCH', 'KNSL', 'JNPR', 'KEP', 'PFGC', 'FMS', 'DINO', 'UHS', 'RL', 'NVT', 'ALLY', 'RRX', 'UHAL.B', 'EQH', 'ALLE', 'EDR', 'HII', 'ELF', 'PCOR', 'AEG', 'REXR', 'TWLO', 'COTY', 'AES', 'GL', 'UWMC', 'TPR', 'SCI', 'AFG', 'PAYC', 'EMN', 'ESTC', 'FIX', 'CPT', 'ONON', 'SBS', 'DAY', 'ITT', 'TREX', 'TFX', 'PAG', 'BBWI', 'HEI', 'MOS', 'FBIN', 'CNM', 'CTLT', 'CUBE', 'CLF', 'CLH', 'U', 'BXP', 'ALV', 'APG', 'FTI', 'INFA', 'THC', 'WTRG', 'NLY', 'BJ', 'UNM', 'QGEN', 'WPP', 'CHE', 'WEX', 'STN', 'BSAC', 'TPX', 'GWRE', 'SKX', 'AU', 'AIZ', 'XPEV', 'BF.A', 'CCK', 'JEF', 'COHR', 'TTC', 'ATR', 'SNX', 'VIPS', 'GLOB', 'BWXT', 'CW', 'X', 'ASR', 'KNX', 'PEN', 'TIMB', 'PSO', 'PNW', 'STVN', 'BIRK', 'JLL', 'AGCO', 'PSN', 'ONTO', 'WF', 'EGP', 'PRI', 'DCI', 'GPK', 'MUSA', 'HLI', 'EXP', 'SKM', 'ARMK', 'SSD', 'GPS', 'RHI', 'NCLH', 'WBS', 'HESM', 'MTN', 'FRT', 'YMM', 'S', 'CACI', 'WCC', 'KBR', 'FMC', 'LEA', 'FHN', 'ORI', 'TAL', 'SN', 'AS', 'DLB', 'LAD', 'AYI', 'BRBR', 'MTDR', 'SITE', 'AR', 'TX', 'BIO', 'PVH', 'SWN', 'ELAN', 'RRC', 'CHWY', 'W', 'RBC', 'MHK', 'SF', 'INGR', 'EHC', 'NNN', 'OHI', 'OSK', 'EVR', 'CR', 'GMED', 'LEVI', 'BWA', 'CAVA', 'CIEN', 'KT', 'AXTA', 'HST', 'MSA', 'FN', 'SUM', 'COLD', 'NOV', 'FCN', 'DAR', 'NYT', 'SQM', 'VOYA', 'AIT', 'DDS', 'YPF', 'BILL', 'IVZ', 'BERY', 'CIVI', 'AZEK', 'FR', 'KGC', 'OLN', 'CFR', 'STAG', 'GNRC', 'FOUR', 'MTZ', 'UI', 'RHP', 'BFAM', 'IBP', 'OGE', 'WTS', 'WFG', 'BRX', 'CMA', 'RLI', 'NE', 'HRB', 'ARW', 'MUR', 'VNT', 'ALSN', 'BEP', 'PBF', 'AM', 'FLR', 'WAL', 'ICL', 'ATKR', 'KVYO', 'AN', 'STWD', 'TNET', 'ANF', 'WH', 'PAC', 'POST', 'CAE', 'UGP', 'TMHC', 'ATI', 'CSAN', 'SSB', 'CHH', 'MNSO', 'GTLS', 'CMC', 'HXL', 'ADT', 'G', 'TKR', 'BC', 'BROS', 'BYD', 'VFC', 'ESNT', 'OBDC', 'ESAB', 'GXO', 'GIL', 'BXSL', 'WHR', 'ESI', 'ENLC', 'NEU', 'MLI', 'FLS', 'OMF', 'FAF', 'MTH', 'PB', 'VVV', 'SNV', 'BRFS', 'M', 'BLCO', 'KNTK', 'TRNO', 'SON', 'LPX', 'MTG', 'ADC', 'DV', 'DTM', 'SMAR', 'INSP', 'PHI', 'PLNT', 'RH', 'MSM', 'AA', 'AGI', 'THO', 'HOG', 'ZWS', 'CPRI', 'PDI', 'SM', 'ST', 'RITM', 'CLS', 'SPXC', 'AWI', 'SEE', 'KBH', 'AXS', 'AMG', 'SUN', 'UGI', 'KOF', 'FSK', 'PAAS', 'PII', 'DOCS', 'ALTM', 'KEX', 'SWX', 'AL', 'JHG', 'MMS', 'FRO', 'BCC', 'SFB', 'HR', 'VAL', 'ALIT', 'GGB', 'RYN', 'CADE', 'AGO', 'R', 'LEN.B', 'ALK', 'VNO', 'KD', 'SKY', 'MGY', 'ETRN', 'ATH PR A', 'SSL', 'BHVN', 'HMY', 'FLO', 'FNB', 'CBT', 'HGV', 'FSS', 'RDN', 'ASGN', 'ASH', 'HOMB', 'JXN', 'NFG', 'WFC PR L', 'AAP', 'OGN', 'SLGN', 'CPG', 'GATX', 'MDC', 'CLVT', 'ELC', 'KRG', 'THG', 'RIG', 'LNC', 'FG', 'AIRC', 'PAGS', 'IDA', 'GTES', 'AEO', 'MDU', 'WK', 'WU', 'GME', 'BMI', 'TDW', 'DNB', 'BIPC', 'HRI', 'GBCI', 'LAZ', 'AEL', 'WTM', 'MOG.A', 'CPA', 'SQSP', 'MSGS', 'HUN', 'SIG', 'PFSI', 'IGT', 'BEPC', 'SHAK', 'VMI', 'GKOS', 'KNF', 'MOD', 'EPRT', 'SID', 'FUL', 'BVN', 'BOX', 'ABG', 'TKC', 'AQN', 'PRGO', 'POR', 'PWSC', 'NJR', 'KRC', 'DY', 'ENIC', 'AMR', 'SNDR', 'CWAN', 'ASAI', 'ACA', 'CC', 'APLE', 'HP', 'GOLF', 'ERJ', 'MAIN', 'EURN', 'ORA', 'AB', 'EVH', 'ESMT', 'TEX', 'HAE', 'NXE', 'MC', 'DFH', 'KAI', 'ITGR', 'AVNT', 'DXC', 'STNG', 'HHH', 'VIST', 'BCO', 'WHD', 'KMPR', 'CXM', 'SMG', 'NOG', 'JOBY', 'NVST', 'BAC PR L', 'PBH', 'ENS', 'TDC', 'AI', 'ZGN', 'CBZ', 'STR', 'ERF', 'CIB', 'DOCN', 'MATX', 'CRC', 'SEM', 'GMS', 'NSP', 'SPR', 'KWR', 'GPI', 'ASAN', 'MHO', 'PK', 'MAN', 'BKH', 'SAM', 'CNS', 'ATS', 'CUZ', 'SDRL', 'IRT', 'BDC', 'MAC', 'OGS', 'APAM', 'CVI', 'AYX', 'BXMT', 'SFBS', 'GRP.U', 'WOLF', 'CXT', 'VAC', 'PIPR', 'GFF', 'KTB', 'CIG', 'LBRT', 'HI', 'SBSW', 'KFY', 'TPH', 'RNG', 'BHC', 'ELP', 'ENOV', 'ATHM', 'VTMX', 'REZI', 'JBT', 'PNM', 'YETI', 'ALE', 'SR', 'NPO', 'SLG', 'NEA', 'CNX', 'NNI', 'OSCR', 'PRKS', 'GHC', 'CRS', 'NOMD', 'HIMS', 'DNP', 'UNF', 'BTU', 'BSM', 'TNL', 'CRI', 'CTRE', 'EPR', 'SKT', 'JOE', 'WOR', 'ADNT', 'ASB', 'IFS', 'INST', 'VSH', 'SVV', 'WD', 'HAYW', 'PAY', 'ARCH', 'RLX', 'TCN', 'USM', 'NS', 'HGTY', 'DBRG', 'FHI', 'NSA', 'BUR', 'TEO', 'OR', 'YOU', 'ENV', 'QTWO', 'CSTM', 'SXT', 'AROC', 'SITC', 'LPL', 'ZKH', 'JWN', 'CNO', 'QS', 'AIN', 'HTGC', 'HASI', 'AX', 'DOOR', 'LTH', 'LCII', 'USAC', 'PRMW', 'CCS', 'HCC', 'FBP', 'GNW', 'KSS', 'BRC', 'BNL', 'HL', 'CDP', 'IIPR', 'TFPM', 'MTRN', 'CWT', 'NEP', 'NYCB', 'AWR', 'OUT', 'LRN', 'LXP', 'AVA', 'BTE', 'CWEN', 'ABM', 'NAD', 'TGNA', 'GPOR', 'BMA', 'AMK', 'MPW', 'WNS', 'EBR.B', 'CNMD', 'C PR N', 'MCY', 'BOOT', 'HIW', 'YELP', 'KOS', 'ESE', 'ALB PR A', 'GBTG', 'NHI', 'NVG', 'SPB', 'TROX', 'EGO', 'CABO', 'MODG', 'SLVM', 'AUB', 'TDOC', 'INSW', 'LEG', 'ARCO', 'MP', 'UTZ', 'EXG', 'ALG', 'EVTC', 'GRBK', 'TBBB', 'ABR', 'BOH', 'MWA', 'RXO', 'VSTS', 'CBU', 'SG', 'NABL', 'ADX', 'OI', 'PGTI', 'HBM', 'MANU', 'CEIX', 'GVA', 'TALO', 'DNA', 'MCW', 'MTX', 'AESI', 'NZF', 'CAAP', 'PJT', 'TIXT', 'BANC', 'COUR', 'CRK', 'CPK', 'CNK', 'AIR', 'CWH', 'MBC', 'DQ', 'ZETA', 'SHO', 'RAMP', 'CPE', 'GETY', 'BE', 'AMN', 'DEI', 'MIR', 'PARR', 'CCU', 'CALX', 'CWK', 'ATMU WI', 'FCPT', 'FUN', 'VZIO', 'ROG', 'CUK', 'FL', 'ATMU', 'WSO.B', 'SIX', 'PRIM', 'AGL', 'FIHL', 'PTY', 'EAT', 'UTF', 'PD', 'JBI', 'TGLS', 'DAVA', 'PAM', 'TRN', 'CIG.C', 'SXI', 'OII', 'TNC', 'AMBP', 'ENR', 'ETY', 'SPNT', 'TGH', 'LSPD', 'BOWL', 'NPWR', 'SWI', 'EQC', 'GDV', 'TAC', 'BKU', 'XPRO', 'GOTU', 'HTH', 'HNI', 'IONQ', 'BSBR', 'THS', 'KGS', 'GOF', 'KMT', 'DRH', 'UE', 'SCL', 'ATGE', 'CRGY', 'BKE', 'B', 'OMI', 'TSLX', 'PEB', 'BFH', 'WGO', 'VSTO', 'EPC', 'HBI', 'ERO', 'USA', 'OBDE', 'VTLE', 'RLJ', 'JPM PR C', 'DFIN', 'DKL', 'SJW', 'MNR', 'FOR', 'VET', 'BB', 'TNK', 'MSDL', 'SSTK', 'AZZ', 'MSGE', 'UAA', 'BIGZ', 'NUV', 'EPAC', 'AGM', 'COMP', 'GRND', 'VYX', 'UP', 'SAH', 'FSLY', 'CODI', 'VGR', 'BMEZ', 'ENVA', 'BORR', 'PHIN', 'DHT', 'DK', 'SGHC', 'WMK', 'GNL', 'LOB', 'ECAT', 'RCUS', 'EE', 'DAN', 'WLY', 'EVT', 'VRTS', 'GIC', 'KAR', 'BCAT', 'OFG', 'SPHR', 'IVT', 'LU', 'JPM PR D', 'AKR', 'BIO.B', 'TDS', 'NGVT', 'RNST', 'GSBD', 'STC', 'PRO', 'OXM', 'CXW', 'SDHC', 'FBK', 'LUMN', 'VTEX', 'SFL', 'UA', 'BBUC', 'JELD', 'GEF', 'SMR', 'CUBI', 'JPM PR M', 'RVT', 'GAB', 'TV', 'USPH', 'SEMR', 'JPM PR L', 'ESRT', 'NAC', 'KYN', 'TY', 'RES', 'BBAR', 'CNNE', 'ACHR', 'RQI', 'ARI', 'GLP', 'LZB', 'TARO', 'APO PR A', 'JBGS', 'AG', 'BBU', 'DNOW', 'HG', 'CWEN.A', 'BYON', 'GEO', 'IAG', 'LPG', 'RC', 'GBX', 'RVLV', 'WS', 'LVWR', 'XHR', 'BDJ', 'VSCO', 'WFC PR Z', 'FINV', 'NEE PR R', 'WKC', 'HLX', 'BTT', 'CDRE', 'GTY', 'SCS', 'T PR C', 'PAR', 'PDO', 'SAND', 'KRP', 'STEW', 'HLIO', 'BSTZ', 'SAFE', 'BAK', 'JKS', 'HMN', 'MSC', 'NTB', 'ETV', 'GEF.B', 'NATL', 'EVEX', 'PRG', 'KN', 'VVX', 'HYT', 'ETG', 'FLNG', 'LTC', 'NWN', 'LADR', 'LGF.B', 'MLNK', 'CTS', 'CAL', 'GES', 'DAC', 'ASPN', 'GENI', 'VRE', 'FCF', 'BXMX', 'WRBY', 'KLG', 'BAC PR B', 'AGTI', 'TWO', 'CMRE', 'SPH', 'CMTG', 'KRO', 'TR', 'GEL', 'RSI', 'KEN', 'OEC', 'UHAL', 'DSL', 'DO', 'CDE', 'KAMN', 'WT', 'ZUO', 'PHR', 'SBH', 'NBHC', 'MAX', 'CDLR', 'AAT', 'AKO.B', 'JPM PR K', 'MMI', 'CTOS', 'NMM', 'LNN', 'GOOS', 'DBD', 'ATUS', 'STEL', 'BAC PR M', 'CGAU', 'BST', 'NTST', 'UVV', 'PMT', 'ETWO', 'ET PR I', 'WNC', 'COF PR I', 'HE', 'GS PR D', 'NIC', 'ZIM', 'LMND', 'MEG', 'ENFN', 'DEA', 'ZIP', 'CEPU', 'ELME', 'NFJ', 'NX', 'ALEX', 'BAC PR N', 'FDP', 'SA', 'BKD', 'MFA', 'NRP', 'SHCO', 'MKC.V', 'KW', 'FSCO', 'NMZ', 'TUYA', 'HCI', 'CARS', 'NVGS', 'BNRE.A', 'ARLO', 'KOP', 'HUYA', 'DOLE', 'PFS', 'EIG', 'AGRO', 'UMH', 'CIM', 'ALL PR H', 'AIV', 'ATEN', 'USB PR A', 'BHE', 'FBRT', 'FPF', 'AMRC', 'ALX', 'GAM', 'ECVT', 'PTA', 'MUC', 'TGI', 'EOS', 'RYI', 'T PR A', 'NAPA', 'MS PR O', 'FSM', 'MS PR P', 'TDCX', 'BLX', 'WTTR', 'MRC', 'BBN', 'BCSF', 'BXC', 'BTZ', 'BAC PR Q', 'PGRE', 'DUK PR A', 'MS PR A', 'MS PR I', 'HY', 'AKO.A', 'BZH', 'MODN', 'WFC PR A', 'NI PR B', 'BBDC', 'REVG', 'RNP', 'BRCC', 'MS PR K', 'PLYM', 'COF PR J', 'EFC', 'MATV', 'THR', 'WFC PR D', 'C PR J', 'SYF PR A', 'GRC', 'BHLB', 'IDT', 'USNA', 'GB', 'NRK', 'ARR', 'PX', 'ECO', 'AMPS', 'SLCA', 'ACEL', 'HRT', 'NEXA', 'IHS', 'HPP', 'SII', 'BV', 'MTUS', 'PRM', 'HLF', 'NCDL', 'AHH', 'BFS', 'NBXG', 'OBK', 'RSKD', 'AMC', 'BY', 'PDX', 'SXC', 'LAC', 'PRLB', 'AWF', 'AVNS', 'MQY', 'SBR', 'IMAX', 'BRSP', 'BAC PR O', 'PDS', 'ETW', 'GNK', 'AHR', 'KIND', 'FIGS', 'LC', 'MUI', 'FVRR', 'MS PR E', 'OLO', 'AOD', 'BGS', 'MS PR F', 'TGS', 'USB PR H', 'BSIG', 'AVAL', 'AZUL', 'CII', 'GHLD', 'MET PR F', 'BAC PR K', 'CSR', 'ETD', 'DLX', 'WFC PR R', 'NAT', 'CAPL', 'CMP', 'UTL', 'WEAV', 'CHGG', 'THQ', 'AORT', 'CCO', 'HQH', 'LGF.A', 'VLRS', 'BRDG', 'LAAC', 'RWT', 'NBR', 'SBOW', 'LOMA', 'WWW', 'PSFE', 'UTI', 'JPM PR J', 'SPLP', 'ET PR E', 'GRNT', 'WFC PR C', 'PUMP', 'RGR', 'PDM', 'WLKP', 'TFC PR R', 'MET PR E', 'DRQ', 'MD', 'HOV', 'NXRT', 'MYI', 'MYE', 'NGL', 'EXTO', 'FNA', 'BDN', 'ML', 'ARIS', 'REX', 'AXL', 'BCX', 'EOI', 'ELPC', 'TWI', 'JQC', 'EVRI', 'SCHW PR D', 'EFXT', 'VVI', 'WDI', 'JPC', 'CLB', 'DLY', 'LDI', 'STT PR D', 'PHK', 'DX', 'CHCT', 'IGR', 'CHPT', 'RNR PR F', 'AMTB', 'ECC', 'DCO', 'DIN', 'PBI', 'SMWB', 'VTOL', 'NOAH', 'ASIX', 'EQH PR A', 'NLY PR F', 'PCN', 'RA', 'NOA', 'UNFI', 'TNP', 'AC', 'CBL', 'DRD', 'SOC', 'XPOF', 'GSL', 'FFC', 'HKD', 'GS PR K', 'YEXT', 'JMIA', 'BAC PR P', 'KREF', 'EGLE', 'NXP', 'PFLT', 'GS PR A', 'BNRE', 'VTS', 'PAXS', 'UAN', 'AMBC', 'HZO', 'CLW', 'YALA', 'IIIN', 'INN', 'SMP', 'HTD', 'HOUS', 'WFC PR Y', 'SPCE', 'ASC', 'AIO', 'AACT', 'TPC', 'AGX', 'VMO', 'MEGI', 'NVRI', 'TK', 'NDMO', 'NUS', 'BLND', 'ALL PR J', 'BOE', 'VVR', 'DDD', 'DESP', 'MHD', 'PGRU', 'MTAL', 'PFN', 'BALY', 'PL', 'MUJ', 'WSR', 'PRA', 'DBI', 'IFN', 'BAC PR S', 'IRS', 'NEE PR N', 'NIE', 'CLCO', 'TRTX', 'ATH PR C', 'CION', 'NR', 'BIT', 'GMRE', 'CEM', 'SCE PR M', 'UVE', 'BME', 'NMCO', 'LDP', 'PDT', 'BHK', 'JXN PR A', 'PBT', 'MET PR A', 'PEO', 'WCC PR A', 'NOVA', 'USB PR P', 'PACK', 'ETJ', 'USB PR R', 'RBCP', 'PKST', 'LNC PR D', 'BGY', 'LZM', 'SMRT', 'SB', 'DEC', 'PML', 'DAO', 'IIM', 'BTO', 'TTI', 'PLOW', 'NKX', 'GATO', 'MLR', 'EMD', 'CPAC', 'SES', 'VEL', 'EHAB', 'TFC PR O', 'QD', 'NPK', 'KEY PR L', 'BBAI', 'VGM', 'LXU', 'MPLN', 'VKQ', 'BGB', 'TXO', 'PSBD', 'AACT.U', 'GPRK', 'FTHY', 'NUVB', 'WIW', 'UHT', 'ATH PR E', 'STK', 'DSU', 'BLE', 'GTN', 'FPI', 'ALL PR B', 'NVRO', 'FC', 'EB', 'SRG', 'DIAX', 'CINT', 'ODC', 'SCHW PR J', 'EBF', 'MYD', 'CPF', 'IQI', 'ACCO', 'SD', 'SYF PR B', 'VTN', 'BLW', 'NXJ', 'BOC', 'AIG PR A', 'EMO', 'EAF', 'SAVE', 'PSA PR L', 'HLLY', 'CLDT', 'THW', 'JFR', 'GUG', 'EQBK', 'XPER', 'RF PR B', 'COF PR L', 'AXS PR E', 'TPB', 'EXK', 'AQNU', 'HVT', 'MOG.B', 'HPS', 'FUBO', 'STT PR G', 'GHY', 'YRD', 'LND', 'OLP', 'SUPV', 'KEY PR I', 'BUI', 'SOS', 'VCV', 'GDOT', 'MTW', 'SRI', 'EGY', 'PSA PR P', 'MEI', 'WDH', 'NRDY', 'VPG', 'ALCC', 'MS PR L', 'RF PR C', 'BFK', 'BANC PR F', 'HIPO', 'MMD', 'MVF', 'GOL', 'MCS', 'FRA', 'ZH', 'NBB', 'ORC', 'IVR', 'ATH PR D', 'RMT', 'MMU', 'FFWM', 'ASGI', 'PNNT', 'NLY PR I', 'GNE', 'NQP', 'MUX', 'TRC', 'ISD', 'HPI', 'MCB', 'HFRO', 'JPI', 'OSG', 'MOV', 'VHI', 'NLY PR G', 'FEI', 'RITM PR D', 'MUA', 'CURV', 'LAW', 'KODK', 'NPFD', 'MLP', 'ACRE', 'AVK', 'GBLI', 'ETO', 'GUT', 'CLVT PR A', 'MYN', 'GTLS PR B', 'CNDB.U', 'IGD', 'NGVC', 'UZD', 'EVN', 'SKE', 'GBAB', 'OPY', 'NMAI', 'BH', 'ETB', 'CYH', 'CSV', 'SCE PR L', 'FSD', 'NS PR B', 'GAMI', 'SGU', 'MED', 'SABA', 'DFP', 'GHI', 'NYCB PR A', 'TDS PR V', 'CFG PR E', 'HIO', 'NFYS.U', 'RNR PR G', 'CTO', 'ROSS.U', 'EFR', 'KEY PR K', 'USB PR S', 'FFA', 'AEL PR A', 'ZTR', 'SDHY', 'LEO', 'BFAC.U', 'MCI', 'WTI', 'UZE', 'CVEO', 'TRTL.U', 'EEX', 'MPX', 'TBI', 'ACP', 'NGL PR B', 'ANRO', 'KIO', 'HQL', 'SOI', 'BFZ', 'CYD', 'GFR', 'RITM PR C', 'SMBK', 'USB PR Q', 'OIS', 'BBW', 'KEY PR J', 'RRAC', 'BGR', 'BML PR L', 'RERE', 'KTF', 'DPG', 'TPVG', 'NLOP', 'SAN PR B', 'AGS', 'SMHI', 'ALTG', 'HSHP', 'HPF', 'DSX', 'HIG PR G', 'QBTS', 'SOR', 'EFT', 'RFMZ', 'TCI', 'PPT', 'SNV PR E', 'UIS', 'PMO', 'MBI', 'XFLT', 'FRGE', 'GNTY', 'NAN', 'RRAC.U', 'PSA PR R', 'MIY', 'WLYB', 'TYG', 'MHN', 'GHG', 'PFL', 'DDL', 'AWP', 'ARDC', 'EDN', 'RLJ PR A', 'ADCT', 'MYTE', 'AVD', 'YSG', 'PSTL', 'NL', 'ASG', 'HYLN', 'LANV', 'CIM PR B', 'FOF', 'JRI', 'DLR PR L', 'SCM', 'AFB', 'RFI', 'EDD', 'SAR', 'ARL', 'PERF', 'BRW', 'PKE', 'DBRG PR I', 'FINS', 'HYAC.U', 'HYAC', 'OIA', 'COF PR N', 'COOK', 'BRT', 'HIX', 'CFG PR D', 'GCI', 'ATH PR B', 'SCE PR J', 'MIN', 'GCO', 'BYM', 'PSA PR I', 'KCGI.U', 'HBB', 'STEM', 'VOYA PR B', 'SNDA', 'PSA PR G', 'BAC PR E', 'AEL PR B', 'RMM', 'BGT', 'NPCT', 'ASA', 'TDS PR U', 'NCV', 'RF PR E', 'SLQT', 'LEV', 'PMM', 'NCA', 'JGH', 'OPFI', 'CNDA.U', 'TWN', 'SCE PR K', 'BGH', 'SPIR', 'DSM', 'PSA PR H', 'DBRG PR J', 'RCS', 'NRGV', 'AHL PR C', 'TRTL', 'SPXX', 'PSA PR F', 'FIF', 'ORN', 'SCE PR H', 'ALL PR I', 'CTR', 'RITM PR B', 'HYI', 'LXFR', 'ONTF', 'CTV', 'JILL', 'AMWL', 'UMH PR D', 'MXF', 'MG', 'TDF', 'MCR', 'GHM', 'AL PR A', 'AEVA', 'CAF', 'WBX', 'RYAM', 'MMT', 'DBL', 'FCT', 'AOMR', 'TRAK', 'MEC', 'EOT', 'BML PR H', 'BNY', 'QUAD', 'SJT', 'WNNR.U', 'WOW', 'BKT', 'HRTG', 'TEI', 'SCD', 'PMX', 'PGSS.U', 'AMPX', 'RCFA.U', 'DSAQ.U', 'LCW.U', 'IPI', 'RIV', 'RNGR', 'CPS', 'EMP', 'KIM PR M', 'TRIS.U', 'PMF', 'QVCC', 'PORT.U', 'FF', 'BKDT', 'SR PR A', 'GPMT', 'HPP PR C', 'OSI.U', 'MIXT', 'NREF', 'NUW', 'TVC', 'VPV', 'ACV', 'KREF PR A', 'AMPY', 'AGD', 'KFS', 'MTB PR H', 'TVE', 'MFA PR C', 'PSF', 'CRD.A', 'RLTY', 'TWO PR B', 'MQT', 'GAQ.U', 'LLAP', 'MSB', 'NXDT', 'RM', 'NS PR A', 'PSA PR J', 'BARK', 'MVT', 'AGM.A', 'IIF', 'CNDA', 'TWO PR C', 'BFLY', 'AFT', 'OPAD', 'JRS', 'JCE', 'FET', 'TSI', 'MUE', 'PHYT.U', 'SF PR C', 'OOMA', 'NC', 'NGS', 'JOF', 'PHT', 'TLYS', 'SF PR D', 'EQH PR C', 'NCZ', 'MFM', 'FPH', 'DTC', 'NOTE', 'ATCO PR H', 'WRB PR G', 'ALLG', 'NMG', 'AIF', 'SEDA.U', 'ABR PR F', 'OAK PR B', 'CIM PR C', 'RDW', 'AHL PR D', 'WAL PR A', 'VLN', 'SLG PR I', 'BKN', 'FBRT PR E', 'AAN', 'PINE', 'KIM PR L', 'LGI', 'SMLP', 'ODV', 'CANG', 'MX', 'PSA PR N', 'DM', 'KIM PR N', 'DDT', 'EP PR C', 'OUST', 'ENO', 'XYF', 'FREY', 'NSA PR A', 'DLR PR K', 'PSA PR K', 'AHL PR E', 'BH.A', 'HIE', 'MHI', 'DBRG PR H', 'BKKT', 'SPNT PR B', 'NTG', 'ETX', 'NPV', 'SNV PR D', 'VNO PR M', 'SEDA', 'EOD', 'BKSY', 'PSA PR S', 'PEB PR G', 'PEB PR H', 'MAV', 'PMT PR C', 'OPP', 'CLBR', 'BHV', 'OCN', 'CIM PR D', 'DMB', 'ONL', 'GAM PR B', 'KNOP', 'BML PR J', 'APCA.U', 'PCK', 'VNO PR L', 'BSL', 'MNTN.U', 'WIA', 'GDO', 'MIO', 'SST', 'IGI', 'EMF', 'SCE PR G', 'CMS PR C', 'GS PR C', 'VNO PR N', 'PSA PR M', 'TSE', 'DLR PR J', 'PMT PR B', 'SBXC', 'IFIN.U', 'PCQ', 'DOUG', 'TRIS', 'TNP PR F', 'VBF', 'CLBR.U', 'CBD', 'IVR PR C', 'MITT', 'APCA', 'CIO', 'NS PR C', 'TRTN PR C', 'DHF', 'FPL', 'FSR', 'PZC', 'HGLB', 'GNL PR D', 'INSI', 'PRE PR J', 'MFA PR B', 'TSQ', 'SEAL PR B', 'MPV', 'HYB', 'OAK PR A', 'ASB PR E', 'O PR', 'GAQ', 'ABR PR D', 'GRX', 'LCW', 'FT', 'SITC PR A', 'AUB PR A', 'EHI', 'TAP.A', 'CBH', 'NFYS', 'DNMR', 'FLC', 'GGT', 'VNO PR O', 'NNY', 'MPA', 'SF PR B', 'IDE', 'TEAF', 'BGX', 'PHYT', 'PIM', 'RMAX', 'AHH PR A', 'BIP PR A', 'SPLP PR A', 'CRD.B', 'SKLZ', 'RITM PR A', 'TFC PR I', 'MCN', 'BFAC', 'IFIN', 'TGH PR A', 'TGH PR B', 'PNST', 'MKFG', 'EVTL', 'BIP PR B', 'BMN', 'GF', 'MSD', 'GNL PR A', 'BEP PR A', 'TRTN PR D', 'TRTN PR B', 'TRTN PR E', 'ARGO PR A', 'BWG', 'STG', 'ARR PR C', 'EIC', 'EVG', 'MHF', 'CCZ', 'CNF', 'CADE PR A', 'WNNR', 'FHN PR E', 'LICY', 'GPMT PR A', 'GWH', 'TG', 'MDV', 'SPE', 'FRT PR C', 'IGA', 'AMTD', 'BTA', 'CNDB', 'NYCB PR U', 'TRTX PR C', 'CATO', 'INN PR E', 'BHR', 'RMMZ', 'PSQH', 'PFD', 'DMO', 'ALUR', 'ARGD', 'EVC', 'AIU', 'UGIC', 'WEL.U', 'MNTN', 'FMN', 'DCF', 'PEB PR F', 'ADC PR A', 'NAZ', 'DRH PR A', 'JHS', 'SEAL PR A', 'PSA PR O', 'EARN', 'DSAQ', 'WEA', 'ROSS', 'AXR', 'WBS PR G', 'GLOP PR A', 'SBXC.U', 'KCGI', 'HEQ', 'EQC PR D', 'TNP PR E', 'ATCO PR D', 'WBS PR F', 'CMRE PR E', 'DHX', 'KF', 'BOH PR A', 'PHD', 'OPA', 'BHG', 'LFT', 'CTA PR B', 'TWO PR A', 'RCFA', 'CIM PR A', 'SCX', 'EPR PR G', 'PCF', 'SOL', 'GDV PR K', 'GSL PR B', 'CFR PR B', 'EBS', 'BIG', 'ACR PR C', 'CXE', 'PAI', 'CIA', 'PORT', 'JHI', 'AMH PR H', 'PHX', 'PGSS', 'ARC', 'SBI', 'NIM', 'MVO', 'AMH PR G', 'BW', 'EFC PR A', 'BW PR A', 'PSEC PR A', 'PFO', 'FTK', 'DX PR C', 'PMT PR A', 'MITT PR C', 'HFRO PR A', 'ABR PR E', 'IVR PR B', 'FHN PR F', 'AGM PR F', 'WHG', 'AJX', 'EPR PR C', 'UFI', 'SWZ', 'CMRE PR D', 'BGSF', 'CHN', 'VOC', 'RMI', 'DLNG', 'AGM PR G', 'CMRE PR C', 'ACR PR D', 'CLDT PR A', 'TWOA', 'CHMI', 'CRT', 'IH', 'EFC PR B', 'CODI PR B', 'GGZ', 'CODI PR C', 'MGF', 'CODI PR A', 'NMT', 'FHN PR D', 'EVF', 'PCM', 'SHO PR H', 'SRL', 'NXG', 'BFS PR E', 'CCRD', 'GNL PR E', 'CSR PR C', 'KSM', 'RFM', 'COF PR K', 'AGM PR D', 'EFC PR C', 'IHD', 'GDL', 'JLS', 'PEB PR E', 'OSI', 'EPR PR E', 'OCFT', 'TPZ', 'CCIF', 'CMU', 'GNL PR B', 'GAB PR H',

# 20240315 버전

In [1]:
import requests
from bs4 import BeautifulSoup ##html 싹 가져와주는 애
from selenium import webdriver ##웹드라이버 돌려주는애
import pandas as pd
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from sklearn.feature_extraction.text import CountVectorizer

In [2]:
firm_df= pd.read_excel('/Users/jonghyunkim/repo/Tristan/S&P 500 Companies (Standard and Poor 500).xlsx')
firm_df

    Symbol                   Name                  Sector
0      MMM                     3M             Industrials
1      AOS            A. O. Smith             Industrials
2      ABT                 Abbott             Health Care
3     ABBV                 AbbVie             Health Care
4      ACN              Accenture  Information Technology
..     ...                    ...                     ...
516   PENN     Penn Entertainment                     NaN
517     UA  Under Armour(Class C)                     NaN
518    UAA  Under Armour(Class A)                     NaN
519   IPGP          IPG Photonics                     NaN
520    GPS                    Gap                     NaN

[521 rows x 3 columns]

In [3]:
import FinanceDataReader as fdr
df_nyse = fdr.StockListing('NYSE')
df_nasdaq = fdr.StockListing('NASDAQ')

100%|██████████| 2838/2838 [00:06<00:00, 468.54it/s]
100%|██████████| 3834/3834 [00:05<00:00, 704.77it/s]

In [4]:
nyse_list = list(df_nyse['Symbol'])
nasdaq_list = list(df_nasdaq['Symbol'])

In [5]:
driver = webdriver.Chrome('/Users/jonghyunkim/repo/Tristan/chromedriver')

/var/folders/3m/s0ysqyzs3fb_mcgvm4wjzt3w0000gn/T/ipykernel_54850/118248137.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('/Users/jonghyunkim/repo/Tristan/chromedriver')

In [6]:
driver.maximize_window()
url = 'https://www.fool.com/'
driver.get(url)
time.sleep(3)

In [7]:
def scroll_down_until_clickable(driver, element):
    while not element.is_enabled():
        # Scroll down by simulating the PAGE_DOWN key
        driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.ARROW_DOWN)
        # Add a wait to allow content to load
        # WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "your_element_selector")))
        
def scroll_up_until_clickable(driver, element):
    while not element.is_enabled():
        # Scroll down by simulating the PAGE_DOWN key
        driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.ARROW_UP)
        # Add a wait to allow content to load
        # WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "your_element_selector")))

In [8]:
def scroll_up_and_click(driver, element):
    while True:
        try:
            element.click()
            break
        except:
            driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.ARROW_UP)

def scroll_down_and_click(driver, element):
    while True:
        try:
            element.click()
            break
        except:
            driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.ARROW_DOWN)

In [16]:
symbol = []
name = []
web_tickers = []
years = []
quarters = []
target_texts = []
esg_word_count = []
sustainability_word_count = []
res_man_word_count = []

checking = pd.read_excel('SeokJun Collection_renewal_체크포인트용.xlsx')
checking2 = pd.read_excel('SeokJun Collection_renewal_체크포인트용2.xlsx')
checking3 = pd.read_excel('SeokJun Collection_renewal_체크포인트용3.xlsx')
checking4 = pd.read_excel('SeokJun Collection_renewal_체크포인트용4.xlsx')
checking5 = pd.read_excel('SeokJun Collection_renewal_체크포인트용5.xlsx')
checking6 = pd.read_excel('SeokJun Collection_renewal_체크포인트용6.xlsx')
checking7 = pd.read_excel('SeokJun Collection_renewal_체크포인트용7.xlsx')
for index, row in firm_df.iterrows():
    if row['Symbol'] in list(checking['Symbol']):
        continue
    elif row['Symbol'] in list(checking2['Symbol']):
        continue
    elif row['Symbol'] in list(checking3['Symbol']):
        continue    
    elif row['Symbol'] in list(checking4['Symbol']):
        continue  
    elif row['Symbol'] in list(checking5['Symbol']):
        continue  
    elif row['Symbol'] in list(checking6['Symbol']):
        continue  
    elif row['Symbol'] in list(checking7['Symbol']):
        continue
    sym = row['Symbol']
    if sym in nyse_list:
        market = 'nyse'
    elif sym in nasdaq_list:
        market = 'nasdaq'
    else:
        symbol.append(row['Symbol'])
        name.append(row['Name'])
        web_tickers.append('not in market')
        years.append('error')
        quarters.append('error')
        target_texts.append('error')
        esg_word_count.append('error')
        sustainability_word_count.append('error')
        res_man_word_count.append('error')
        continue

    new_url = f'https://www.fool.com/quote/{market}/{sym.lower()}/'
    driver.get(new_url)
    time.sleep(2)
    try:
        Title = driver.find_element(By.XPATH, '/html/body/div[9]/div[3]/div[1]/section[1]/div[1]/header/div/div[2]/h1').text
    except:
        symbol.append(row['Symbol'])
        name.append(row['Name'])
        web_tickers.append('not in market')
        years.append('error')
        quarters.append('error')
        target_texts.append('error')
        esg_word_count.append('error')
        sustainability_word_count.append('error')
        res_man_word_count.append('error')
        continue

    web_ticker = Title.split(': ')[-1][:-1]

    new_url2 = f'https://www.fool.com/quote/{market}/{sym.lower()}/#quote-earnings-transcripts'
    try:
        driver.get(new_url2)
        time.sleep(4) # 페이지 로딩 대기
    except:
        symbol.append(row['Symbol'])
        name.append(row['Name'])
        web_tickers.append(web_ticker)
        years.append('error')
        quarters.append('error')
        target_texts.append('error')
        esg_word_count.append('error')
        sustainability_word_count.append('error')
        res_man_word_count.append('error')
        continue



    try:
    ## View more earnings transcript 버튼 누르기 2번
        try:
            driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button').click()
            time.sleep(4)
            driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.PAGE_DOWN)
            time.sleep(2)

        except:
            scroll_down_until_clickable(driver, driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button'))
            # for l in range(10):
            #     driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.ARROW_DOWN)
            driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button').click()
            time.sleep(4)
            # time.sleep(1)
            # driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button').click()
            driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.PAGE_DOWN)

            time.sleep(2)
        try:
            driver.find_element(By.XPATH, '//*[@id="quote-earnings-transcripts"]/button').click()
            time.sleep(1)
        except:
            pass
        driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.PAGE_UP)
        time.sleep(1)
        for l in range(10):
            driver.find_element(By.CSS_SELECTOR, 'body').send_keys(Keys.ARROW_UP)
        time.sleep(1)
    except:
        driver.get(new_url2)
        time.sleep(4) # 페이지 로딩 대기
        
    try:
        ## 각 earnings transcript의 path 가져오기
        path_list = driver.find_element(By.ID, 'quote-earnings-transcripts').find_elements(By.CLASS_NAME, 'mb-6')
    except:
        symbol.append(row['Symbol'])
        name.append(row['Name'])
        web_tickers.append(web_ticker)
        years.append('error')
        quarters.append('error')
        target_texts.append('error')
        esg_word_count.append('error')
        sustainability_word_count.append('error')
        res_man_word_count.append('error')
        continue

    ## 각 path의 제목들 가져오기 (언제건지 확인용)
    candidate_list = [path_list[n].text for n in range(len(path_list))]


    ## 2023년과 2021년에 해당하는 애들 가져오기
    i = 0
    target_indexs = []
    for c in candidate_list:
        if '2023' in c:
            target_indexs.append(i)
        elif '2021' in c:
            target_indexs.append(i)
        i += 1
    
    for k in target_indexs:
        try:
            # scroll_up_until_clickable(driver, path_list[k])
            # path_list[k].click()
            scroll_up_and_click(driver, path_list[k])
        except:
            # scroll_down_until_clickable(driver, path_list[k])
            # time.sleep(2)
            # path_list[k].click()
            scroll_down_and_click(driver, path_list[k])

        time.sleep(2)
        
        symbol.append(row['Symbol'])
        name.append(row['Name'])
        web_tickers.append(web_ticker)
        try:
        ## 위에서 가져온 path 제목에서 quarter와 year 골라내서 추가하기
            if web_ticker == row['Symbol']:
                title_texts = candidate_list[k].split('(' + web_ticker + ')')[1].split()
            # title_texts = candidate_list[k].split(')')[1].split()
            else:
                title_texts = candidate_list[k].split('(' + row['Symbol'] + ')')[1].split()
        except:
            title_texts = candidate_list[k].split(')')[1].split()

        quarter = title_texts[0]
        year = title_texts[1]

        years.append(year)
        quarters.append(quarter)
        
        ## 텍스트 가져와서 소문자화 등 전처리 한 후 고유 단어 개수세기
        target_text = driver.find_element(By.CLASS_NAME, 'article-body').text
        target_text = target_text.replace('\n', ' ')
        target_texts.append(target_text)

        target_text = target_text.lower()
        
        vectorizer = CountVectorizer(ngram_range=(1,2))
        vec_reviews = vectorizer.fit_transform([target_text])
        vec_terms = vectorizer.get_feature_names_out()
        vec_df = pd.DataFrame(vec_reviews.toarray(), columns=vec_terms)

        if 'esg' in vec_df.columns:
            esg_count = vec_df['esg']
        else:
            esg_count = 0

        esg_word_count.append(esg_count)

        if 'sustainability' in vec_df.columns:
            sus_count = vec_df['sustainability']
        else:
            sus_count = 0
        
        sustainability_word_count.append(sus_count)


        if 'responsible management' in vec_df.columns:
            res_man_count = vec_df['responsible management']
        else:
            res_man_count = 0
        
        res_man_word_count.append(res_man_count)

        driver.back()
        time.sleep(2)
    
    final_data = pd.DataFrame({'Symbol' : symbol, 'Name' : name, 'Website_ticker' : web_tickers, 'Year' : years, 'Quarter' : quarters, 'Raw Text' : target_texts, 'ESG' : esg_word_count, 'Sustainability' : sustainability_word_count, 'Responsible Management' : res_man_word_count})
    final_data.to_excel('SeokJun Collection_renewal_체크포인트용8.xlsx')

In [17]:
driver.quit()

In [18]:
checking8 = pd.read_excel('SeokJun Collection_renewal_체크포인트용8.xlsx')

In [19]:
data = pd.concat([checking, checking2, checking3, checking4, checking5, checking6, checking7, checking8])
data

,Unnamed: 0,Symbol,Name,Website_ticker,Year,Quarter,Raw Text,ESG,Sustainability,Responsible Management
0,0,MMM,3M,MMM,2023,Q4,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,0,"0 4\nName: sustainability, dtype: int64",0
1,1,MMM,3M,MMM,2023,Q3,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,0,"0 2\nName: sustainability, dtype: int64",0
2,2,MMM,3M,MMM,2023,Q2,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,0,"0 2\nName: sustainability, dtype: int64",0
3,3,MMM,3M,MMM,2021,Q4,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,"0 2\nName: esg, dtype: int64","0 11\nName: sustainability, dtype: int64",0
4,4,MMM,3M,MMM,2021,Q3,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,0,"0 9\nName: sustainability, dtype: int64",0
...,...,...,...,...,...,...,...,...,...,...
1696,1696,GPS,Gap,GPS,2023,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,0,0,0
1697,1697,GPS,Gap,GPS,2021,Q4,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,"0 1\nName: esg, dtype: int64","0 1\nName: sustainability, dtype: int64",0
1698,1698,GPS,Gap,GPS,2021,Q3,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,0,"0 1\nName: sustainability, dtype: int64",0
1699,1699,GPS,Gap,GPS,2021,Q2,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,0,0,0
1700,1700,GPS,Gap,GPS,2021,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,0,"0 1\nName: sustainability, dtype: int64",0

In [20]:
data.reset_index(inplace=True, drop=True)

In [21]:
data['ESG'][3]

'0    2\nName: esg, dtype: int64'

In [22]:
ESG = []
SUSTAINABILITY = []
RESPONSIBLE_MANAGEMENT = []

for index, row in data.iterrows():
    if row['ESG'] == 'error':
        ESG.append(row['ESG'])
    else:
        if type(row['ESG']) == str:
            ESG.append(row['ESG'].split()[1])
        else:
            ESG.append(row['ESG'])

    if row['Sustainability'] == 'error':
        SUSTAINABILITY.append(row['Sustainability'])
    else:
        if type(row['Sustainability']) == str:
            SUSTAINABILITY.append(row['Sustainability'].split()[1])
        else:
            SUSTAINABILITY.append(row['Sustainability'])

    if row['Responsible Management'] == 'error':
        RESPONSIBLE_MANAGEMENT.append(row['Responsible Management'])
    else:
        if type(row['Responsible Management']) == str:
            RESPONSIBLE_MANAGEMENT.append(row['Responsible Management'].split()[1])
        else:
            RESPONSIBLE_MANAGEMENT.append(row['Responsible Management'])
            

print(len(ESG))
print(len(SUSTAINABILITY))
print(len(RESPONSIBLE_MANAGEMENT))

2306
2306
2306

In [23]:
data['ESG'] = ESG
data['Sustainability'] = SUSTAINABILITY
data['Responsible Management'] = RESPONSIBLE_MANAGEMENT
data

,Unnamed: 0,Symbol,Name,Website_ticker,Year,Quarter,Raw Text,ESG,Sustainability,Responsible Management
0,0,MMM,3M,MMM,2023,Q4,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,0,4,0
1,1,MMM,3M,MMM,2023,Q3,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,0,2,0
2,2,MMM,3M,MMM,2023,Q2,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,0,2,0
3,3,MMM,3M,MMM,2021,Q4,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,2,11,0
4,4,MMM,3M,MMM,2021,Q3,IMAGE SOURCE: THE MOTLEY FOOL. 3M (MMM 1.82%) ...,0,9,0
...,...,...,...,...,...,...,...,...,...,...
2301,1696,GPS,Gap,GPS,2023,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,0,0,0
2302,1697,GPS,Gap,GPS,2021,Q4,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,1,1,0
2303,1698,GPS,Gap,GPS,2021,Q3,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,0,1,0
2304,1699,GPS,Gap,GPS,2021,Q2,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,0,0,0
2305,1700,GPS,Gap,GPS,2021,Q1,IMAGE SOURCE: THE MOTLEY FOOL. Gap (GPS 2.56%)...,0,1,0

In [26]:
data.drop(columns='Unnamed: 0', inplace=True)

In [27]:
data.to_excel('Earnings call data_2021 and 2023_ S&P500.xlsx', index_label = False)